export const tribes = ['Couple', 'Family', 'Friends', 'Solo'];
export const moods = ['Wildlife', 'Cultural', 'Himalayan', 'Coastal', 'Spiritual', 'Heritage', 'Nature', 'Adventure'];

export const categories = [
  {
    id: 'wildlife',
    title: 'The Safari Collection',
    description: 'Track the legendary Bengal tiger and Asiatic lion from the comfort of India’s most exclusive jungle lodges—where conservation meets uncompromising luxury.',
    image: 'https://images.unsplash.com/photo-1581012771300-224937651c42?w=800&q=80',
    icon: '🐯',
    color: '#A38B71',
    count: 2,
  },
  {
    id: 'birding',
    title: 'The Birder\'s Sanctuary',
    description: 'Experience India’s avian wonders on private, expert-led expeditions to the subcontinent’s most prolific birding hotspots—from the Himalayas to the tropical south.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    icon: '🦅',
    color: '#6D7E6A',
    count: 1,
  },
  {
    id: 'photography',
    title: 'Photography Expeditions',
    description: 'Master the art of light and life on journeys curated for the visual storyteller, led by world-class photographers in India’s most photogenic landscapes.',
    image: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=800&q=80',
    icon: '📸',
    color: '#3B4A5A',
    count: 1,
  },
  {
    id: 'heritage',
    title: 'Royal Heritage',
    description: 'Immerse yourself in the soul of India through private audiences with artisans, scholars, and royalty, ensuring a deep connection to living traditions.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80',
    icon: '🏰',
    color: '#8C6A4A',
    count: 0,
  },
  {
    id: 'spiritual',
    title: 'Spiritual Pilgrimages',
    description:
      'Follow sacred rivers, temple bells, and living traditions from the Ganges ghats to the Golden Temple — with unhurried pacing, private guides, and stays that honour both comfort and contemplation.',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1400&q=85',
    icon: '🕉️',
    color: '#5C4A6B',
    count: 1,
  },
];

export const tours = [
  {
    slug: 'the-grand-tiger-expedition',
    title: 'The Grand Tiger Expedition',
    category: 'wildlife',
    region: 'Ranthambore & Bandhavgarh',
    duration: '12 Days',
    groupSize: 'Private Journey',
    price: 9200,
    rating: 5.0,
    reviews: 84,
    featured: true,
    badge: 'Signature Collection',
    image: 'https://images.unsplash.com/photo-1581012771300-224937651c42?w=800&q=80',
    description: 'A masterpiece of wildlife travel. Follow the tiger’s secret paths in Ranthambore and Bandhavgarh, staying in opulent jungle camps that recall the era of the Raj. Our expert naturalists ensure every sighting is a deep revelation of the wild.',
    highlights: ['Senior Naturalist as Private Lead', 'Aman-i-Khas Tented Suites', 'Private Tracking Vehicles', 'No Tipping Policy Throughout'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Delhi', body: 'VIP meet-and-greet, private transfer, and a gentle settling-in at a signature hotel.' },
      { day: 'Day 2', title: 'Ranthambore — first drives', body: 'Morning and afternoon safaris with a senior naturalist; unhurried pacing and private vehicle.' },
      { day: 'Day 3', title: 'Ranthambore', body: 'A full day in the park with flexible timing for light, weather, and sightings.' },
      { day: 'Day 4', title: 'Bandhavgarh transfer', body: 'Seamless door-to-door logistics; arrive in time for an evening at camp.' },
      { day: 'Days 5–10', title: 'Bandhavgarh safaris', body: 'Multiple game drives, curated hides (where permitted), and natural history briefings tailored to you.' },
      { day: 'Day 11', title: 'Departure', body: 'Private transfer onward with a complete trip dossier and next-step planning.' },
    ],
    tribes: ['Couple', 'Family', 'Solo'],
    moods: ['Wildlife', 'Nature', 'Adventure'],
  },
  {
    slug: 'the-lion-of-sasan-gir',
    title: 'The Lion of Sasan: Gir Safari',
    category: 'wildlife',
    region: 'Gir National Park, Gujarat',
    duration: '6 Days',
    groupSize: 'Only for You',
    price: 6400,
    rating: 4.9,
    reviews: 38,
    featured: true,
    badge: 'Exclusive Access',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&q=80',
    description: 'Track the last bastion of the Asiatic Lion in the dry jungles of Gujarat. This private expedition offers unparalleled access to the forest’s heart, staying in an ultra-luxury lodge that blends modern comfort with timeless wilderness.',
    highlights: ['Private Sightings with Head Trackers', 'The Postcard Gir Luxury Stay', 'Bespoke Desert Dining Experiences', 'Tribal Interaction with Maldharis'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Gujarat', body: 'Private transfer to Gir; sunset drinks and safari briefing.' },
      { day: 'Days 2–5', title: 'Gir safaris + cultural moments', body: 'Morning and afternoon drives, Maldhari community encounters, and restorative lodge time between outings.' },
      { day: 'Day 6', title: 'Depart', body: 'Transfer onward with flexible routing based on your next destination.' },
    ],
    tribes: ['Couple', 'Family', 'Friends'],
    moods: ['Wildlife', 'Nature', 'Adventure'],
  },
  {
    slug: 'himalayan-avian-masterclass',
    title: 'Himalayan Avian Masterclass',
    category: 'birding',
    region: 'Pangot & Sattal',
    duration: '8 Days',
    groupSize: 'Private Specialist',
    price: 5800,
    rating: 5.0,
    reviews: 26,
    featured: true,
    badge: 'Species Focus',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    description: 'A pilgrimage for the elite birder. Focus on rare Himalayan species — from the Cheer Pheasant to the Great Slaty Woodpecker. Led by India’s top ornithologists, this journey combines technical precision with luxury lodge comforts.',
    highlights: ['Private Lead Ornithologist', 'Specialist High-Altitude Gear Provided', 'Private Hide Photography Access', 'Fully Inclusive — No Hidden Costs'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & orient', body: 'Settle in, review target species list, and prep optics and hides.' },
      { day: 'Days 2–7', title: 'Pangot & Sattal', body: 'Dawn birding sessions, flexible field time, and expert-led identification workshops.' },
      { day: 'Day 8', title: 'Depart', body: 'Optional extension planning for further Himalayan habitats.' },
    ],
    tribes: ['Solo', 'Friends'],
    moods: ['Nature', 'Birding', 'Himalayan'],
  },
  {
    slug: 'photography-shadows-of-the-ghats',
    title: 'Shadows of the Ghats: Photography',
    category: 'photography',
    region: 'Western Ghats',
    duration: '9 Days',
    groupSize: 'Small Group (Max 4)',
    price: 7500,
    rating: 4.9,
    reviews: 42,
    featured: false,
    badge: 'Artist Series',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&q=88',
    description: 'Master the macro and the majestic. Join a world-renowned wildlife photographer to capture the endemic life of the Western Ghats. Focused on slow observation and technical mastery in India’s most biodiverse hotspot.',
    highlights: ['Lead by NatGeo Contributor', 'Macro & Landscape Workshops', 'Private Jungle River Cruises', 'Premium Equipment Concierge'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & workshop', body: 'Gear check, style review, and a golden-hour shoot to establish your baseline.' },
      { day: 'Days 2–8', title: 'Field days', body: 'Macro sessions, landscape timing, low-impact hides, and daily image reviews with your mentor.' },
      { day: 'Day 9', title: 'Final edits & depart', body: 'A curated portfolio handoff and next-step recommendations for future expeditions.' },
    ],
    tribes: ['Solo', 'Friends'],
    moods: ['Nature', 'Photography', 'Adventure'],
  },
  {
    slug: 'souls-of-the-north-luxury-spiritual',
    title: 'Souls of the North: Luxury Spiritual Circuit',
    category: 'spiritual',
    region: 'Delhi · Rishikesh · Punjab · Varanasi · Bundelkhand · Rajasthan',
    duration: '19 Days',
    groupSize: 'Private Journey',
    price: 18900,
    rating: 5.0,
    reviews: 0,
    featured: true,
    badge: 'Sacred India',
    image: 'https://images.unsplash.com/photo-1695956353120-54ce5e91632b?auto=format&fit=crop&w=1400&q=85',
    description:
      'A nineteen-day private pilgrimage through North India’s spiritual spine: the Ganges at Rishikesh and Varanasi, the Golden Temple at Amritsar, erotic-sculpture temples at Khajuraho, the riverside forts of Orchha, the cliff citadel of Gwalior, regal Dholpur, the Taj at Agra, and the Pink City of Jaipur — with curated yoga, aartis, temple access, and heritage stays at a pace built for international travellers.',
    highlights: [
      'Private chauffeured road legs with airport-style meet-and-greets',
      'Ganga Aarti in Rishikesh & Varanasi (premium viewing where available)',
      'Dedicated yoga & pranayama sessions with vetted instructors in Rishikesh',
      'Golden Temple (Harmandir Sahib) at dawn & dusk with expert Sikh heritage guide',
      'Domestic flights: Amritsar–Varanasi & Varanasi–Khajuraho (routing refined at booking)',
      'Khajuraho UNESCO temples + optional evening classical dance',
      'Orchha palaces & chhatris, Gwalior Fort, heritage stay in Dholpur',
      'Taj Mahal sunrise/sunset planning, Agra Fort, Fatehpur Sikri en route to Jaipur',
      'Jaipur: Amber, City Palace, observatory, artisan and spiritual storytelling',
    ],
    itinerary: [
      {
        day: 'Day 1',
        title: 'Delhi — Arrival & soft landing',
        body: 'VIP airport meet, private transfer to a premium city hotel (e.g. Oberoi / Leela / Imperial). Light briefing over dinner; optional short evening drive past India Gate if jet lag allows.',
      },
      {
        day: 'Day 2',
        title: 'Delhi — Faith & empire in the capital',
        body: 'Private tour of Old Delhi (Jama Masjid, heritage lanes) with respectful dress guidance; afternoon Qutub Minar complex or Humayun’s Tomb. Evening at leisure — spa or early night before the hills.',
      },
      {
        day: 'Day 3',
        title: 'Delhi → Rishikesh — Into the Himalayan foothills',
        body: 'Scenic private drive (~6 hrs) with comfort stops. Late-afternoon check-in at a top riverside or estate retreat. Sunset Ganga Aarti at Parmarth Niketan or Triveni Ghat (your guide secures calm viewing).',
      },
      {
        day: 'Days 4–5',
        title: 'Rishikesh — Yoga, Ganga & sacred forest',
        body: 'Two full days: sunrise yoga and pranayama at your stay; guided walks to key ashrams; optional Beatles Ashram (Maharishi) with storytelling; temple visits (Bharat Mandir, Trayambakeshwar as interests align). Second evening: second Aarti experience or private meditation block — pacing stays unhurried.',
      },
      {
        day: 'Day 6',
        title: 'Rishikesh → Chandigarh — From river to planned city',
        body: 'Morning yoga optional, then private drive to Chandigarh. Afternoon: Le Corbusier’s Capitol Complex (UNESCO) and Rock Garden with an architecture-focused guide. Overnight at Chandigarh’s best hotel.',
      },
      {
        day: 'Day 7',
        title: 'Chandigarh → Amritsar — Toward the Golden Temple',
        body: 'Private road to Amritsar (~4–5 hrs). Evening: first immersion at Harmandir Sahib — marble walkways, kirtan, and the glow of the sanctum after dark. Stay within easy reach of the Old City.',
      },
      {
        day: 'Day 8',
        title: 'Amritsar — Dawn, langar & memory',
        body: 'Pre-dawn return to the Golden Temple for Amrit Velā; participate in langar if you wish. Later: Jallianwala Bagh and curated Old City walk. Optional Wagah border (late afternoon) — we’ll advise on pacing. Second night in Amritsar.',
      },
      {
        day: 'Day 9',
        title: 'Amritsar → Varanasi (flight) — The eternal city',
        body: 'Transfer to airport; fly to Varanasi (often via Delhi — we book the smoothest connection). Evening: introduction to the ghats and a major Ganga Aarti (Dashashwamedh or a quieter ghat per your preference) with reserved seating assistance when possible.',
      },
      {
        day: 'Days 10–11',
        title: 'Varanasi — Boats, Sarnath & silk',
        body: 'Sunrise private boat on the Ganges; walking exploration of core ghats and shrines with a cultural-spiritual guide. Full day for Sarnath (where the Buddha first taught), museum, and stupas. Visit a master silk weaver’s home. Second evening: repeat or alternate Aarti, or a classical music baithak if you prefer sound over crowds.',
      },
      {
        day: 'Day 12',
        title: 'Varanasi → Khajuraho (flight)',
        body: 'Morning at leisure or optional last boat. Fly to Khajuraho. Afternoon orientation of the Western Group (UNESCO) with an art-historian angle — symbolism, not sensationalism. Overnight at the finest available lodge/hotel.',
      },
      {
        day: 'Day 13',
        title: 'Khajuraho — Temples & living culture',
        body: 'Eastern & Jain temple clusters; village craft visit. Optional evening: sound-and-light or classical dance at an intimate venue. Rest before Bundelkhand’s fort towns.',
      },
      {
        day: 'Day 14',
        title: 'Khajuraho → Orchha — Riverside palaces',
        body: 'Private drive to Orchha (~3 hrs). Fort complex, Jahangir Mahal, riverside chhatris, Ram Raja Temple legend. Stay in a restored palace or heritage hotel overlooking the Betwa.',
      },
      {
        day: 'Day 15',
        title: 'Orchha → Gwalior — Cliff-top fort',
        body: 'Morning light in Orchha, then drive to Gwalior. Gwalior Fort: Man Mandir, Sas-Bahu temples, Teli-ka-Mandir with rock-cut Jain figures. Overnight at a premium city or palace hotel.',
      },
      {
        day: 'Day 16',
        title: 'Gwalior → Dholpur — Quiet regal Rajasthan',
        body: 'Drive to Dholpur — red sandstone country, birdlife, and the Chambal. Check into a heritage palace hotel; afternoon property walk, high tea, or gentle nature drive. A breathing day before the Taj.',
      },
      {
        day: 'Day 17',
        title: 'Dholpur → Agra — Taj timing',
        body: 'Private drive to Agra. Afternoon: Agra Fort and Mehtab Bagh across the Yamuna for Taj silhouette at sunset. Oberoi Amarvilas or equivalent for iconic views and service.',
      },
      {
        day: 'Day 18',
        title: 'Agra → Jaipur via Fatehpur Sikri',
        body: 'Sunrise Taj Mahal visit with timed entry and private guide. Continue to Fatehpur Sikri — Buland Darwaza, Jama Masjid, Jodha Bai’s palace. Arrive Jaipur for a relaxed evening and royal Rajasthani dinner.',
      },
      {
        day: 'Day 19',
        title: 'Jaipur → Delhi — Departure',
        body: 'Morning Amber Fort (jeep or elephant per policy/season), City Palace, Jantar Mantar. Afternoon private road or flight to Delhi for international connection; day-use room arranged if needed. Safe travels — you leave with North India’s sacred geography mapped in memory.',
      },
    ],
    tribes: ['Couple', 'Family', 'Solo', 'Friends'],
    moods: ['Spiritual', 'Heritage', 'Cultural', 'Himalayan'],
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Lady Alexandra Thorne',
    role: 'Journalist & Explorer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    tour: 'The Grand Tiger Expedition',
    rating: 5,
    text: 'NatIndia did not just show us tigers; they invited us into a secret world. Their naturalists possess a depth of knowledge that transformed every drive into a masterclass in ecology.',
  },
  {
    id: 2,
    name: 'Julian & Elena Vance',
    role: 'Philanthropists',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    tour: 'The Lion of Sasan: Gir Safari',
    rating: 5,
    text: 'A flawless orchestration of logistics and wilderness. Having private access to the Asiatic Lion trackers was a privilege beyond words. The definitive way to experience the heart of Gujarat.',
  },
];

export const stats = [
  { value: '35+', label: 'Years of Luxury Heritage' },
  { value: '100%', label: 'Private & Bespoke' },
  { value: '24/7', label: 'Personal Concierge' },
  { value: 'Luxe', label: 'World’s Best Nominee' },
];
