export const tribes = ['Couple', 'Family', 'Friends', 'Solo'];
export const moods = ['Wildlife', 'Cultural', 'Himalayan', 'Coastal', 'Spiritual', 'Heritage', 'Nature', 'Adventure'];

export const categories = [
  {
    id: 'wildlife',
    title: 'The Safari Collection',
    description: 'Track the legendary Bengal tiger and Asiatic lion from the comfort of India’s most exclusive jungle lodges—where conservation meets uncompromising luxury.',
    image: 'https://images.unsplash.com/photo-1581012771300-224937651c42?w=800&q=80',
    icon: '🐯',
    color: '#A38B71',
    count: 2,
  },
  {
    id: 'birding',
    title: 'The Birder\'s Sanctuary',
    description: 'Experience India’s avian wonders on private, expert-led expeditions to the subcontinent’s most prolific birding hotspots—from the Himalayas to the tropical south.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    icon: '🦅',
    color: '#6D7E6A',
    count: 1,
  },
  {
    id: 'photography',
    title: 'Photography Expeditions',
    description: 'Master the art of light and life on journeys curated for the visual storyteller, led by world-class photographers in India’s most photogenic landscapes.',
    image: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=800&q=80',
    icon: '📸',
    color: '#3B4A5A',
    count: 1,
  },
  {
    id: 'heritage',
    title: 'Royal Heritage',
    description: 'Immerse yourself in the soul of India through private audiences with artisans, scholars, and royalty, ensuring a deep connection to living traditions.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80',
    icon: '🏰',
    color: '#8C6A4A',
    count: 0,
  },
  {
    id: 'spiritual',
    title: 'Spiritual Pilgrimages',
    description:
      'Follow sacred rivers, temple bells, and living traditions from the Ganges ghats to the Golden Temple — with unhurried pacing, private guides, and stays that honour both comfort and contemplation.',
    image: 'https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=1400&q=85',
    icon: '🕉️',
    color: '#5C4A6B',
    count: 1,
  },
  {
    id: 'coastal',
    title: 'Coastal Escapes',
    description:
      'Drift from the Coromandel shore to French bougainvillea, Chola stone, Chettinad mansions, temple drums in Madurai, misty tea country, and finally Kerala’s backwaters — ending in colonial Cochin.',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=1400&q=85',
    icon: '🌊',
    color: '#2D6A7A',
    count: 1,
  },
  {
    id: 'himalayan',
    title: 'Himalayan Adventures',
    description:
      'Thin air, cobalt lakes, and passes that touch the sky — from Leh’s palaces and gompas to Nubra’s dunes and Pangong’s shifting blues, with room for wildlife, culture, and pure mountain drama.',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85',
    icon: '🏔️',
    color: '#3D5A80',
    count: 1,
  },
  {
    id: 'cultural',
    title: 'Cultural Journeys',
    description:
      'Trace the living pulse of India through ancient stone, tribal traditions, sacred forests, and centuries-old craft — private journeys that connect you to the subcontinent’s most authentic stories.',
    image: 'https://images.unsplash.com/photo-1651927059928-156e0a1d49d8?auto=format&fit=crop&w=1400&q=85',
    icon: '🏛️',
    color: '#7A5C3A',
    count: 1,
  },
];

export const tours = [
  {
    slug: 'the-grand-tiger-expedition',
    title: 'The Grand Tiger Expedition',
    category: 'wildlife',
    region: 'Ranthambore & Bandhavgarh',
    duration: '12 Days',
    groupSize: 'Private Journey',
    price: 9200,
    rating: 5.0,
    reviews: 84,
    featured: true,
    badge: 'Signature Collection',
    image: 'https://images.unsplash.com/photo-1581012771300-224937651c42?w=800&q=80',
    description: 'A masterpiece of wildlife travel. Follow the tiger’s secret paths in Ranthambore and Bandhavgarh, staying in opulent jungle camps that recall the era of the Raj. Our expert naturalists ensure every sighting is a deep revelation of the wild.',
    highlights: ['Senior Naturalist as Private Lead', 'Aman-i-Khas Tented Suites', 'Private Tracking Vehicles', 'No Tipping Policy Throughout'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Delhi', body: 'VIP meet-and-greet, private transfer, and a gentle settling-in at a signature hotel.' },
      { day: 'Day 2', title: 'Ranthambore — first drives', body: 'Morning and afternoon safaris with a senior naturalist; unhurried pacing and private vehicle.' },
      { day: 'Day 3', title: 'Ranthambore', body: 'A full day in the park with flexible timing for light, weather, and sightings.' },
      { day: 'Day 4', title: 'Bandhavgarh transfer', body: 'Seamless door-to-door logistics; arrive in time for an evening at camp.' },
      { day: 'Days 5–10', title: 'Bandhavgarh safaris', body: 'Multiple game drives, curated hides (where permitted), and natural history briefings tailored to you.' },
      { day: 'Day 11', title: 'Departure', body: 'Private transfer onward with a complete trip dossier and next-step planning.' },
    ],
    tribes: ['Couple', 'Family', 'Solo'],
    moods: ['Wildlife', 'Nature', 'Adventure'],
  },
  {
    slug: 'the-lion-of-sasan-gir',
    title: 'The Lion of Sasan: Gir Safari',
    category: 'wildlife',
    region: 'Gir National Park, Gujarat',
    duration: '6 Days',
    groupSize: 'Only for You',
    price: 6400,
    rating: 4.9,
    reviews: 38,
    featured: true,
    badge: 'Exclusive Access',
    image: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?w=800&q=80',
    description: 'Track the last bastion of the Asiatic Lion in the dry jungles of Gujarat. This private expedition offers unparalleled access to the forest’s heart, staying in an ultra-luxury lodge that blends modern comfort with timeless wilderness.',
    highlights: ['Private Sightings with Head Trackers', 'The Postcard Gir Luxury Stay', 'Bespoke Desert Dining Experiences', 'Tribal Interaction with Maldharis'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive in Gujarat', body: 'Private transfer to Gir; sunset drinks and safari briefing.' },
      { day: 'Days 2–5', title: 'Gir safaris + cultural moments', body: 'Morning and afternoon drives, Maldhari community encounters, and restorative lodge time between outings.' },
      { day: 'Day 6', title: 'Depart', body: 'Transfer onward with flexible routing based on your next destination.' },
    ],
    tribes: ['Couple', 'Family', 'Friends'],
    moods: ['Wildlife', 'Nature', 'Adventure'],
  },
  {
    slug: 'himalayan-avian-masterclass',
    title: 'Himalayan Avian Masterclass',
    category: 'birding',
    region: 'Pangot & Sattal',
    duration: '8 Days',
    groupSize: 'Private Specialist',
    price: 5800,
    rating: 5.0,
    reviews: 26,
    featured: true,
    badge: 'Species Focus',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    description: 'A pilgrimage for the elite birder. Focus on rare Himalayan species — from the Cheer Pheasant to the Great Slaty Woodpecker. Led by India’s top ornithologists, this journey combines technical precision with luxury lodge comforts.',
    highlights: ['Private Lead Ornithologist', 'Specialist High-Altitude Gear Provided', 'Private Hide Photography Access', 'Fully Inclusive — No Hidden Costs'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & orient', body: 'Settle in, review target species list, and prep optics and hides.' },
      { day: 'Days 2–7', title: 'Pangot & Sattal', body: 'Dawn birding sessions, flexible field time, and expert-led identification workshops.' },
      { day: 'Day 8', title: 'Depart', body: 'Optional extension planning for further Himalayan habitats.' },
    ],
    tribes: ['Solo', 'Friends'],
    moods: ['Nature', 'Birding', 'Himalayan'],
  },
  {
    slug: 'photography-shadows-of-the-ghats',
    title: 'Shadows of the Ghats: Photography',
    category: 'photography',
    region: 'Western Ghats',
    duration: '9 Days',
    groupSize: 'Small Group (Max 4)',
    price: 7500,
    rating: 4.9,
    reviews: 42,
    featured: false,
    badge: 'Artist Series',
    image: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1600&q=88',
    description: 'Master the macro and the majestic. Join a world-renowned wildlife photographer to capture the endemic life of the Western Ghats. Focused on slow observation and technical mastery in India’s most biodiverse hotspot.',
    highlights: ['Lead by NatGeo Contributor', 'Macro & Landscape Workshops', 'Private Jungle River Cruises', 'Premium Equipment Concierge'],
    itinerary: [
      { day: 'Day 1', title: 'Arrive & workshop', body: 'Gear check, style review, and a golden-hour shoot to establish your baseline.' },
      { day: 'Days 2–8', title: 'Field days', body: 'Macro sessions, landscape timing, low-impact hides, and daily image reviews with your mentor.' },
      { day: 'Day 9', title: 'Final edits & depart', body: 'A curated portfolio handoff and next-step recommendations for future expeditions.' },
    ],
    tribes: ['Solo', 'Friends'],
    moods: ['Nature', 'Photography', 'Adventure'],
  },
  {
    slug: 'souls-of-the-north-luxury-spiritual',
    title: 'Souls of the North: Luxury Spiritual Circuit',
    category: 'spiritual',
    region: 'Delhi · Rishikesh · Punjab · Varanasi · Bundelkhand · Rajasthan',
    duration: '19 Days',
    groupSize: 'Private Journey',
    price: 18900,
    rating: 5.0,
    reviews: 0,
    featured: true,
    badge: 'Sacred India',
    image: 'https://images.unsplash.com/photo-1695956353120-54ce5e91632b?auto=format&fit=crop&w=1400&q=85',
    description:
      'A nineteen-day private pilgrimage through North India’s spiritual spine: the Ganges at Rishikesh and Varanasi, the Golden Temple at Amritsar, erotic-sculpture temples at Khajuraho, the riverside forts of Orchha, the cliff citadel of Gwalior, regal Dholpur, the Taj at Agra, and the Pink City of Jaipur — with curated yoga, aartis, temple access, and heritage stays at a pace built for international travellers.',
    highlights: [
      'Private chauffeured road legs with airport-style meet-and-greets',
      'Ganga Aarti in Rishikesh & Varanasi (premium viewing where available)',
      'Dedicated yoga & pranayama sessions with vetted instructors in Rishikesh',
      'Golden Temple (Harmandir Sahib) at dawn & dusk with expert Sikh heritage guide',
      'Domestic flights: Amritsar–Varanasi & Varanasi–Khajuraho (routing refined at booking)',
      'Khajuraho UNESCO temples + optional evening classical dance',
      'Orchha palaces & chhatris, Gwalior Fort, heritage stay in Dholpur',
      'Taj Mahal sunrise/sunset planning, Agra Fort, Fatehpur Sikri en route to Jaipur',
      'Jaipur: Amber, City Palace, observatory, artisan and spiritual storytelling',
    ],
    itinerary: [
      {
        day: 'Day 1',
        title: 'Delhi — Arrival & soft landing',
        body: 'VIP airport meet, private transfer to a premium city hotel (e.g. Oberoi / Leela / Imperial). Light briefing over dinner; optional short evening drive past India Gate if jet lag allows.',
      },
      {
        day: 'Day 2',
        title: 'Delhi — Faith & empire in the capital',
        body: 'Private tour of Old Delhi (Jama Masjid, heritage lanes) with respectful dress guidance; afternoon Qutub Minar complex or Humayun’s Tomb. Evening at leisure — spa or early night before the hills.',
      },
      {
        day: 'Day 3',
        title: 'Delhi → Rishikesh — Into the Himalayan foothills',
        body: 'Scenic private drive (~6 hrs) with comfort stops. Late-afternoon check-in at a top riverside or estate retreat. Sunset Ganga Aarti at Parmarth Niketan or Triveni Ghat (your guide secures calm viewing).',
      },
      {
        day: 'Days 4–5',
        title: 'Rishikesh — Yoga, Ganga & sacred forest',
        body: 'Two full days: sunrise yoga and pranayama at your stay; guided walks to key ashrams; optional Beatles Ashram (Maharishi) with storytelling; temple visits (Bharat Mandir, Trayambakeshwar as interests align). Second evening: second Aarti experience or private meditation block — pacing stays unhurried.',
      },
      {
        day: 'Day 6',
        title: 'Rishikesh → Chandigarh — From river to planned city',
        body: 'Morning yoga optional, then private drive to Chandigarh. Afternoon: Le Corbusier’s Capitol Complex (UNESCO) and Rock Garden with an architecture-focused guide. Overnight at Chandigarh’s best hotel.',
      },
      {
        day: 'Day 7',
        title: 'Chandigarh → Amritsar — Toward the Golden Temple',
        body: 'Private road to Amritsar (~4–5 hrs). Evening: first immersion at Harmandir Sahib — marble walkways, kirtan, and the glow of the sanctum after dark. Stay within easy reach of the Old City.',
      },
      {
        day: 'Day 8',
        title: 'Amritsar — Dawn, langar & memory',
        body: 'Pre-dawn return to the Golden Temple for Amrit Velā; participate in langar if you wish. Later: Jallianwala Bagh and curated Old City walk. Optional Wagah border (late afternoon) — we’ll advise on pacing. Second night in Amritsar.',
      },
      {
        day: 'Day 9',
        title: 'Amritsar → Varanasi (flight) — The eternal city',
        body: 'Transfer to airport; fly to Varanasi (often via Delhi — we book the smoothest connection). Evening: introduction to the ghats and a major Ganga Aarti (Dashashwamedh or a quieter ghat per your preference) with reserved seating assistance when possible.',
      },
      {
        day: 'Days 10–11',
        title: 'Varanasi — Boats, Sarnath & silk',
        body: 'Sunrise private boat on the Ganges; walking exploration of core ghats and shrines with a cultural-spiritual guide. Full day for Sarnath (where the Buddha first taught), museum, and stupas. Visit a master silk weaver’s home. Second evening: repeat or alternate Aarti, or a classical music baithak if you prefer sound over crowds.',
      },
      {
        day: 'Day 12',
        title: 'Varanasi → Khajuraho (flight)',
        body: 'Morning at leisure or optional last boat. Fly to Khajuraho. Afternoon orientation of the Western Group (UNESCO) with an art-historian angle — symbolism, not sensationalism. Overnight at the finest available lodge/hotel.',
      },
      {
        day: 'Day 13',
        title: 'Khajuraho — Temples & living culture',
        body: 'Eastern & Jain temple clusters; village craft visit. Optional evening: sound-and-light or classical dance at an intimate venue. Rest before Bundelkhand’s fort towns.',
      },
      {
        day: 'Day 14',
        title: 'Khajuraho → Orchha — Riverside palaces',
        body: 'Private drive to Orchha (~3 hrs). Fort complex, Jahangir Mahal, riverside chhatris, Ram Raja Temple legend. Stay in a restored palace or heritage hotel overlooking the Betwa.',
      },
      {
        day: 'Day 15',
        title: 'Orchha → Gwalior — Cliff-top fort',
        body: 'Morning light in Orchha, then drive to Gwalior. Gwalior Fort: Man Mandir, Sas-Bahu temples, Teli-ka-Mandir with rock-cut Jain figures. Overnight at a premium city or palace hotel.',
      },
      {
        day: 'Day 16',
        title: 'Gwalior → Dholpur — Quiet regal Rajasthan',
        body: 'Drive to Dholpur — red sandstone country, birdlife, and the Chambal. Check into a heritage palace hotel; afternoon property walk, high tea, or gentle nature drive. A breathing day before the Taj.',
      },
      {
        day: 'Day 17',
        title: 'Dholpur → Agra — Taj timing',
        body: 'Private drive to Agra. Afternoon: Agra Fort and Mehtab Bagh across the Yamuna for Taj silhouette at sunset. Oberoi Amarvilas or equivalent for iconic views and service.',
      },
      {
        day: 'Day 18',
        title: 'Agra → Jaipur via Fatehpur Sikri',
        body: 'Sunrise Taj Mahal visit with timed entry and private guide. Continue to Fatehpur Sikri — Buland Darwaza, Jama Masjid, Jodha Bai’s palace. Arrive Jaipur for a relaxed evening and royal Rajasthani dinner.',
      },
      {
        day: 'Day 19',
        title: 'Jaipur → Delhi — Departure',
        body: 'Morning Amber Fort (jeep or elephant per policy/season), City Palace, Jantar Mantar. Afternoon private road or flight to Delhi for international connection; day-use room arranged if needed. Safe travels — you leave with North India’s sacred geography mapped in memory.',
      },
    ],
    tribes: ['Couple', 'Family', 'Solo', 'Friends'],
    moods: ['Spiritual', 'Heritage', 'Cultural', 'Himalayan'],
  },
  {
    slug: 'coastal-escapes-south-india-chennai-cochin',
    title: 'Coastal Escapes of South India',
    category: 'coastal',
    region: 'Chennai · Coromandel · Pondicherry · Tamil Nadu · Kerala · Cochin',
    duration: '12 Days',
    groupSize: 'Private Journey',
    price: 9450,
    rating: 5.0,
    reviews: 0,
    featured: true,
    badge: 'Coromandel to Malabar',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=88',
    description:
      'Twelve days from Chennai to Cochin — a journey through South India’s serene coastline, colonial heritage, backwaters, temple towns, and tropical landscapes. Unhurried pacing pairs UNESCO rock-cut shrines and Chola grandeur with French Pondicherry, Chettinad mansions, Meenakshi’s night ceremony, Munnar’s tea hills, a private houseboat on the backwaters, and Kathakali in Fort Kochi.',
    highlights: [
      'Chennai: Marina Beach, Fort St. George, Santhome Basilica, Kapaleeshwarar & Mylapore',
      'UNESCO Mahabalipuram: Shore Temple, Five Rathas, Arjuna’s Penance, Krishna’s Butter Ball',
      'Pondicherry: French Quarter, Promenade, Sri Aurobindo Ashram, optional Auroville & cycling',
      'Thanjavur: Brihadeeswarar Temple (UNESCO), palace complex, Saraswathi Mahal Library',
      'Chettinad heritage mansions, crafts, and an authentic regional feast',
      'Madurai: Meenakshi Amman, Nayakkar Palace, markets, evening temple procession',
      'Munnar: tea museum, Eravikulam, Mattupetty, Echo Point, plantation walks',
      'Alleppey: private traditional houseboat — lagoons, villages, Kerala cuisine, sunset on the water',
      'Cochin: Chinese nets, Fort Kochi, St. Francis, Mattancherry Palace, synagogue, spice bazaar, Kathakali',
    ],
    itinerary: [
      {
        day: 'Day 1',
        title: 'Arrival in Chennai — Welcome to South India',
        body: 'Our representative meets you at the airport and transfers you to your hotel. India’s cultural gateway to the south, Chennai blends colonial history, classical traditions, and modern energy. In the afternoon: Marina Beach, Fort St. George, Santhome Basilica, Kapaleeshwarar Temple, and the Mylapore heritage quarter — ending with a traditional South Indian dinner. Overnight in Chennai.',
      },
      {
        day: 'Day 2',
        title: 'Chennai to Mahabalipuram — Along the Coromandel Coast',
        body: 'After breakfast, drive to Mahabalipuram (~2 hours), a UNESCO World Heritage site on the Bay of Bengal. Explore the Shore Temple, Five Rathas, Arjuna’s Penance, Krishna’s Butter Ball, and local stone-carving workshops. Evening free by the beach. Overnight in Mahabalipuram.',
      },
      {
        day: 'Day 3',
        title: 'Mahabalipuram to Pondicherry — French heritage by the sea',
        body: 'Drive south on the scenic East Coast Road to Pondicherry. Visit the French Quarter, Promenade Beach, Sri Aurobindo Ashram, Notre Dame des Anges Church, and colonial streets and cafés. Optional evening cycling in the old town. Overnight in Pondicherry.',
      },
      {
        day: 'Day 4',
        title: 'Pondicherry — Slow travel & coastal elegance',
        body: 'A relaxed day at your pace: optional Auroville and the Matrimandir viewing point, local markets and boutiques, a walk through the Tamil quarter, and time by the sea. Savour the fusion of French and Tamil cultures. Overnight in Pondicherry.',
      },
      {
        day: 'Day 5',
        title: 'Pondicherry to Thanjavur — From coastline to Chola heritage',
        body: 'Drive inland to Thanjavur. Visit the Brihadeeswarar Temple (UNESCO), the royal palace complex, and the Saraswathi Mahal Library — a masterclass in Chola grandeur. Overnight in Thanjavur.',
      },
      {
        day: 'Day 6',
        title: 'Thanjavur to Chettinad — Mansions & culinary traditions',
        body: 'Enter the Chettinad region: heritage mansions, village lanes, antique markets, and craft workshops. Enjoy an authentic Chettinad meal — bold, aromatic, and unforgettable. Overnight in Chettinad.',
      },
      {
        day: 'Day 7',
        title: 'Chettinad to Madurai — The temple city',
        body: 'Continue to one of India’s oldest living cities. Visit Meenakshi Amman Temple, Thirumalai Nayakkar Palace, and flower and spice markets. In the evening, witness the temple’s ceremonial night procession. Overnight in Madurai.',
      },
      {
        day: 'Day 8',
        title: 'Madurai to Munnar — Into the Western Ghats',
        body: 'Ascend into Kerala’s hill country: tea plantations, waterfalls, and misty ridges replace the plains. Evening at leisure in cool mountain air. Overnight in Munnar.',
      },
      {
        day: 'Day 9',
        title: 'Munnar — Tea gardens & mountain serenity',
        body: 'Tea Museum, Eravikulam National Park, Mattupetty Dam, Echo Point, and scenic plantation walks — panoramic views and unhurried time in nature. Overnight in Munnar.',
      },
      {
        day: 'Day 10',
        title: 'Munnar to Alleppey — Kerala backwaters',
        body: 'Descend to Alleppey and board your private traditional houseboat. Glide through coconut lagoons and village life, with regional cuisine on board and sunset over the canals. Overnight on the houseboat.',
      },
      {
        day: 'Day 11',
        title: 'Alleppey to Cochin — Colonial port city',
        body: 'After breakfast, disembark and drive to Cochin. Explore the Chinese fishing nets, Fort Kochi, St. Francis Church, Mattancherry Palace, the Jewish Synagogue, and spice markets. Evening Kathakali performance. Overnight in Cochin.',
      },
      {
        day: 'Day 12',
        title: 'Departure from Cochin — Farewell South India',
        body: 'After breakfast, transfer to Cochin International Airport for your onward flight — taking with you beaches, backwaters, temples, heritage, and tropical calm.',
      },
    ],
    tribes: ['Couple', 'Family', 'Friends', 'Solo'],
    moods: ['Coastal', 'Cultural', 'Heritage', 'Nature'],
  },
  {
    slug: 'himalayan-adventure-ladakh-expedition',
    title: 'Himalayan Adventure: Ladakh Expedition',
    category: 'himalayan',
    region: 'Leh · Nubra Valley · Pangong Lake',
    duration: '6 Days',
    groupSize: 'Private Expedition',
    price: 8750,
    rating: 5.0,
    reviews: 0,
    featured: true,
    badge: 'Roof of the World',
    image: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=1600&q=88',
    description:
      'Six days through Ladakh’s high-altitude theatre — Leh acclimatization, snow leopard–focused outings with expert naturalists, Khardung La into Nubra’s dunes and Diskit, and a night by Pangong’s impossible blues in premium Swiss tents. Culture, wilderness, and photography at a pace that respects the altitude.',
    highlights: [
      'Leh: arrival at one of the world’s highest commercial airports; gentle market walks as you acclimatize',
      'Dedicated snow leopard sighting opportunities with expert naturalists in selected valleys near Leh',
      'Acclimatization day: Leh Palace, Shanti Stupa, bazaar & Ladakhi cafés; second guided wildlife session',
      'Hall of Fame, Pathar Sahib, Magnetic Hill, Indus–Zanskar Sangam, Spituk — plus continued tracking in prime zones',
      'Khardung La crossing into Nubra: Diskit Monastery, Maitreya Buddha, Hunder dunes & Bactrian camels',
      'Full-day Pangong Lake: remote high-altitude scenery, lakeside time, sunset; premium Swiss tent camp',
      'Scenic return to Leh — optional extension or onward flights',
      'Ladakhi culture, Himalayan light, and photography throughout',
    ],
    itinerary: [
      {
        day: 'Day 1',
        title: 'Arrival in Leh — Welcome to the roof of the world',
        body: 'Land at Leh Airport, surrounded by dramatic peaks. Transfer to your hotel and rest for altitude adaptation. If you feel well, a gentle evening stroll in Leh Market. Special focus: first snow leopard–oriented outing in surrounding areas with our expert naturalist team (terrain and conditions permitting). Overnight in Leh.',
      },
      {
        day: 'Day 2',
        title: 'Acclimatization in Leh — Himalayan altitude',
        body: 'A light schedule for safe acclimatization. Late morning: Leh Palace, Shanti Stupa, the local bazaar, and traditional Ladakhi cafés — then free time to rest. Snow leopard experience: second guided observation session in carefully chosen nearby wildlife zones. Overnight in Leh.',
      },
      {
        day: 'Day 3',
        title: 'Leh, Magnetic Hill & Sangam — Culture & tracking',
        body: 'After breakfast: Hall of Fame Museum, Gurudwara Pathar Sahib, Magnetic Hill, the Sangam confluence of the Indus and Zanskar, and Spituk Monastery. Throughout the day, continue dedicated snow leopard tracking with local experts where sightings are most promising — a mix of cultural highlights and high-altitude wildlife focus. Overnight in Leh.',
      },
      {
        day: 'Day 4',
        title: 'Leh to Nubra Valley — Across Khardung La',
        body: 'Drive the legendary Khardung La, among the world’s highest motorable passes, with sweeping Himalayan views. Descend into Nubra — the “valley of flowers” of Ladakh. Visit Diskit Monastery, the giant Maitreya Buddha, Hunder’s sand dunes, and the double-humped Bactrian camel country. Evening under clear mountain skies. Overnight in Nubra Valley.',
      },
      {
        day: 'Day 5',
        title: 'Nubra to Pangong Lake — The jewel of Ladakh',
        body: 'Early departure for Pangong Tso across remote, cinematic landscapes. On arrival, watch the lake’s colours shift through the day. Lakeside exploration, photography, and a peaceful Himalayan sunset from premium Swiss tents at a lakeside camp — a true high wilderness highlight. Overnight at Pangong (Swiss tent camp).',
      },
      {
        day: 'Day 6',
        title: 'Pangong to Leh — Departure or extension',
        body: 'After breakfast, drive back to Leh with final views of rugged ranges and villages. On arrival, transfer for your onward flight or optional extension. Depart with Ladakh’s passes, Pangong’s blues, and snow leopard country etched in memory.',
      },
    ],
    tribes: ['Couple', 'Family', 'Friends', 'Solo'],
    moods: ['Himalayan', 'Adventure', 'Nature', 'Wildlife'],
  },
  {
    slug: 'heart-of-central-india',
    title: 'Heart of Central India',
    category: 'cultural',
    region: 'Bhopal · Sanchi · Pachmarhi · Kanha · Bandhavgarh · Khajuraho · Orchha',
    duration: '12 Days',
    groupSize: 'Private Journey',
    price: 8400,
    rating: 5.0,
    reviews: 0,
    featured: true,
    badge: 'Cultural Journeys',
    image: 'https://images.unsplash.com/photo-1651927059928-156e0a1d49d8?auto=format&fit=crop&w=1600&q=88',
    description:
      'Twelve days through the untamed heart of India — from the Buddhist stupas of Sanchi and the prehistoric caves of Pachmarhi, to tiger-dense jungles of Kanha and Bandhavgarh, the erotic sculptures of Khajuraho, and the riverside forts of Orchha. A journey that weaves wildlife, ancient stone, tribal culture, and living tradition into one unforgettable arc.',
    highlights: [
      'Sanchi: UNESCO Great Stupa with a dedicated Buddhist scholar',
      'Pachmarhi: prehistoric rock art, Satpura hill trails, and hidden waterfalls',
      "Kanha National Park: dawn and dusk safaris in Kipling's Jungle Book landscape",
      "Bandhavgarh: India's highest tiger density, ancient hilltop fort, and Baiga tribal village",
      'Khajuraho: UNESCO Western Group temples with an art historian — symbolism, not sensationalism',
      'Orchha: riverside Mughal palaces, chhatris, and the Ram Raja Temple legend',
      'Private naturalist and cultural guides throughout; no shared vehicles',
      'Curated heritage and jungle lodges at every stage',
    ],
    itinerary: [
      {
        day: 'Day 1',
        title: 'Arrival in Bhopal — City of Lakes',
        body: 'Private airport meet and transfer to your hotel in the City of Lakes. Evening stroll along the Upper Lake at dusk, followed by a welcome dinner of Bhopali cuisine — fiery kebabs and slow-cooked biryanis born from a royal kitchen. Briefing on the journey ahead.',
      },
      {
        day: 'Day 2',
        title: 'Bhopal → Sanchi — The Great Stupa',
        body: "Drive to the UNESCO World Heritage site of Sanchi, home to one of India's oldest stone structures — the Great Stupa commissioned by Emperor Ashoka in the 3rd century BCE. A dedicated Buddhist scholar brings the carved toranas and reliquary mounds to life. Return to Bhopal for the night.",
      },
      {
        day: 'Day 3',
        title: 'Bhopal → Pachmarhi — Into the Satpura Hills',
        body: "Depart for Central India's only hill station, rising into forested Satpura terrain. Afternoon walk to prehistoric rock shelters carrying art from 10,000 years ago. Check into your heritage hill lodge and settle into the cool mountain air.",
      },
      {
        day: 'Day 4',
        title: 'Pachmarhi — Waterfalls, Caves & Rock Art',
        body: 'A full day in Pachmarhi: trek to the hidden Bee Falls, explore the sacred Jata Shankar cave shrine deep in a forest ravine, and visit further painted rock shelters with a local archaeologist. Evening at leisure in the hills.',
      },
      {
        day: 'Day 5',
        title: 'Pachmarhi → Kanha National Park',
        body: "Drive down from the hills and enter the landscape that inspired Rudyard Kipling's Jungle Book. Check into your jungle lodge and join an evening briefing with your senior naturalist. Optional short sunset game drive to settle into the rhythms of the forest.",
      },
      {
        day: 'Day 6',
        title: 'Kanha — Dawn Safari & Barasingha Meadows',
        body: 'Pre-dawn departure for your first full game drive through open meadows carpeted with barasingha (swamp deer) and dense sal forests where Bengal tigers and leopards hunt. Return for breakfast, rest, and an afternoon drive into different zones. Naturalist talk by the fire in the evening.',
      },
      {
        day: 'Day 7',
        title: 'Kanha — Full Day in the Jungle',
        body: 'A second full day of morning and afternoon safaris — flexible pacing lets your naturalist follow fresh tracks, sightings, and optimal light. Kanha is also home to wild dog (dhole), sloth bear, and gaur. Afternoon natural history workshop at the lodge.',
      },
      {
        day: 'Day 8',
        title: 'Kanha → Bandhavgarh — Tiger Country',
        body: "Drive to Bandhavgarh — India's most tiger-dense reserve. Check into your lodge and join an evening briefing. If timing allows, an optional late-afternoon drive to orient you to this more intimate, dramatic landscape of bamboo, sal, and rocky escarpments.",
      },
      {
        day: 'Day 9',
        title: 'Bandhavgarh — Safaris & Ancient Fort',
        body: 'Morning and afternoon game drives through zones with the highest concentration of wild tigers in India. Between drives, visit the ancient Bandhavgarh hilltop fort — a 2,000-year-old citadel with rock-cut Vishnu figures and panoramic forest views. Evening naturalist debrief.',
      },
      {
        day: 'Day 10',
        title: 'Bandhavgarh — Baiga Village & Final Safaris',
        body: "A guided walk into a neighbouring Baiga tribal village — one of India's most ancient indigenous communities — to understand their forest relationship, art, and daily life. Final morning game drive before a private transfer to Khajuraho by road or chartered flight.",
      },
      {
        day: 'Day 11',
        title: 'Khajuraho — Temples of Stone & Devotion',
        body: 'After a relaxed morning, afternoon exploration of the UNESCO Western Group temples with an art historian — a nuanced reading of the Chandela sculptural programme: cosmology, devotion, and the full spectrum of human life rendered in sandstone. Optional evening: classical Kathak dance performance in the temple precinct.',
      },
      {
        day: 'Day 12',
        title: 'Khajuraho → Orchha — Farewell & Departure',
        body: 'Morning visit to the Eastern and Jain temple clusters, quieter and often uncrowded. Drive to Orchha: the riverside Mughal-Rajput fort complex, the Jahangir Mahal, the chhatris lining the Betwa River, and the legendary Ram Raja Temple. Late afternoon transfer to Jhansi railway station or airstrip for onward connections — departing with stone, jungle, and living India woven into memory.',
      },
    ],
    tribes: ['Couple', 'Family', 'Friends', 'Solo'],
    moods: ['Cultural', 'Wildlife', 'Heritage', 'Nature', 'Adventure'],
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Lady Alexandra Thorne',
    role: 'Journalist & Explorer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    tour: 'The Grand Tiger Expedition',
    rating: 5,
    text: 'NatIndia did not just show us tigers; they invited us into a secret world. Their naturalists possess a depth of knowledge that transformed every drive into a masterclass in ecology.',
  },
  {
    id: 2,
    name: 'Julian & Elena Vance',
    role: 'Philanthropists',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    tour: 'The Lion of Sasan: Gir Safari',
    rating: 5,
    text: 'A flawless orchestration of logistics and wilderness. Having private access to the Asiatic Lion trackers was a privilege beyond words. The definitive way to experience the heart of Gujarat.',
  },
];

export const stats = [
  { value: '35+', label: 'Years of Luxury Heritage' },
  { value: '100%', label: 'Private & Bespoke' },
  { value: '24/7', label: 'Personal Concierge' },
  { value: 'Luxe', label: 'World’s Best Nominee' },
];
