export const tribes = ['Couple', 'Family', 'Friends', 'Solo'];
export const moods = ['Wildlife', 'Cultural', 'Himalayan', 'Coastal', 'Spiritual', 'Heritage', 'Nature', 'Adventure'];

export const categories = [
  {
    id: 'wildlife',
    title: 'The Safari Collection',
    description: 'Track the legendary Bengal tiger and Asiatic lion from the comfort of India’s most exclusive jungle lodges—where conservation meets uncompromising luxury.',
    image: 'https://images.unsplash.com/photo-1581012771300-224937651c42?w=800&q=80',
    icon: '🐯',
    color: '#A38B71',
    count: 2,
  },
  {
    id: 'birding',
    title: 'The Birder\'s Sanctuary',
    description: 'Experience India’s avian wonders on private, expert-led expeditions to the subcontinent’s most prolific birding hotspots—from the Himalayas to the tropical south.',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    icon: '🦅',
    color: '#6D7E6A',
    count: 1,
  },
  {
    id: 'photography',
    title: 'Photography Expeditions',
    description: 'Master the art of light and life on journeys curated for the visual storyteller, led by world-class photographers in India’s most photogenic landscapes.',
    image: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=800&q=80',
    icon: '📸',
    color: '#3B4A5A',
    count: 1,
  },
  {
    id: 'heritage',
    title: 'Royal Heritage',
    description: 'Immerse yourself in the soul of India through private audiences with artisans, scholars, and royalty, ensuring a deep connection to living traditions.',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=800&q=80',
    icon: '🏰',
    color: '#8C6A4A',
    count: 0,
  },
];

export const tours = [
  {
    slug: 'the-grand-tiger-expedition',
    title: 'The Grand Tiger Expedition',
    category: 'wildlife',
    region: 'Ranthambore & Bandhavgarh',
    duration: '12 Days',
    groupSize: 'Private Journey',
    price: 9200,
    rating: 5.0,
    reviews: 84,
    featured: true,
    badge: 'Signature Collection',
    image: 'https://images.unsplash.com/photo-1581012771300-224937651c42?w=800&q=80',
    description: 'A masterpiece of wildlife travel. Follow the tiger’s secret paths in Ranthambore and Bandhavgarh, staying in opulent jungle camps that recall the era of the Raj. Our expert naturalists ensure every sighting is a deep revelation of the wild.',
    highlights: ['Senior Naturalist as Private Lead', 'Aman-i-Khas Tented Suites', 'Private Tracking Vehicles', 'No Tipping Policy Throughout'],
    tribes: ['Couple', 'Family', 'Solo'],
    moods: ['Wildlife', 'Nature', 'Adventure'],
  },
  {
    slug: 'the-lion-of-sasan-gir',
    title: 'The Lion of Sasan: Gir Safari',
    category: 'wildlife',
    region: 'Gir National Park, Gujarat',
    duration: '6 Days',
    groupSize: 'Only for You',
    price: 6400,
    rating: 4.9,
    reviews: 38,
    featured: true,
    badge: 'Exclusive Access',
    image: 'https://images.unsplash.com/photo-1614027164847-1b28096a6f54?w=800&q=80',
    description: 'Track the last bastion of the Asiatic Lion in the dry jungles of Gujarat. This private expedition offers unparalleled access to the forest’s heart, staying in an ultra-luxury lodge that blends modern comfort with timeless wilderness.',
    highlights: ['Private Sightings with Head Trackers', 'The Postcard Gir Luxury Stay', 'Bespoke Desert Dining Experiences', 'Tribal Interaction with Maldharis'],
    tribes: ['Couple', 'Family', 'Friends'],
    moods: ['Wildlife', 'Nature', 'Adventure'],
  },
  {
    slug: 'himalayan-avian-masterclass',
    title: 'Himalayan Avian Masterclass',
    category: 'birding',
    region: 'Pangot & Sattal',
    duration: '8 Days',
    groupSize: 'Private Specialist',
    price: 5800,
    rating: 5.0,
    reviews: 26,
    featured: true,
    badge: 'Species Focus',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
    description: 'A pilgrimage for the elite birder. Focus on rare Himalayan species — from the Cheer Pheasant to the Great Slaty Woodpecker. Led by India’s top ornithologists, this journey combines technical precision with luxury lodge comforts.',
    highlights: ['Private Lead Ornithologist', 'Specialist High-Altitude Gear Provided', 'Private Hide Photography Access', 'Fully Inclusive — No Hidden Costs'],
    tribes: ['Solo', 'Friends'],
    moods: ['Nature', 'Birding', 'Himalayan'],
  },
  {
    slug: 'photography-shadows-of-the-ghats',
    title: 'Shadows of the Ghats: Photography',
    category: 'photography',
    region: 'Western Ghats',
    duration: '9 Days',
    groupSize: 'Small Group (Max 4)',
    price: 7500,
    rating: 4.9,
    reviews: 42,
    featured: false,
    badge: 'Artist Series',
    image: 'https://images.unsplash.com/photo-1533038590840-1cde6e668a91?w=800&q=80',
    description: 'Master the macro and the majestic. Join a world-renowned wildlife photographer to capture the endemic life of the Western Ghats. Focused on slow observation and technical mastery in India’s most biodiverse hotspot.',
    highlights: ['Lead by NatGeo Contributor', 'Macro & Landscape Workshops', 'Private Jungle River Cruises', 'Premium Equipment Concierge'],
    tribes: ['Solo', 'Friends'],
    moods: ['Nature', 'Photography', 'Adventure'],
  },
];

export const testimonials = [
  {
    id: 1,
    name: 'Lady Alexandra Thorne',
    role: 'Journalist & Explorer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&q=80',
    tour: 'The Grand Tiger Expedition',
    rating: 5,
    text: 'NatIndia did not just show us tigers; they invited us into a secret world. Their naturalists possess a depth of knowledge that transformed every drive into a masterclass in ecology.',
  },
  {
    id: 2,
    name: 'Julian & Elena Vance',
    role: 'Philanthropists',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&q=80',
    tour: 'The Lion of Sasan: Gir Safari',
    rating: 5,
    text: 'A flawless orchestration of logistics and wilderness. Having private access to the Asiatic Lion trackers was a privilege beyond words. The definitive way to experience the heart of Gujarat.',
  },
];

export const stats = [
  { value: '35+', label: 'Years of Luxury Heritage' },
  { value: '100%', label: 'Private & Bespoke' },
  { value: '24/7', label: 'Personal Concierge' },
  { value: 'Luxe', label: 'World’s Best Nominee' },
];
